from com.android.monkeyrunner import MonkeyRunner, MonkeyDevice, MonkeyImage
import checkpic
import pprint
caseName='Chat'

import os

device = MonkeyRunner.waitForConnection(5,'c0808a31e28199f')
device1 = MonkeyRunner.waitForConnection(5,'HT26GV801821')
#device2 = MonkeyRunner.waitForConnection(5,'')
#device3 = MonkeyRunner.waitForConnection(5,'')

def init():
	os.system('adb -s c0808a31e28199f shell am force-stop com.kabam.fortress')
	os.system('adb -s HT26GV801821 shell am force-stop com.kabam.fortress')
	device.startActivity('com.kabam.fortress/.KBNActivity')
	device1.startActivity('com.kabam.fortress/.KBNActivity')
	MonkeyRunner.sleep(10)
	device.touch(200,50,'DOWN_AND_UP')
	device1.touch(200,50,'DOWN_AND_UP')
	MonkeyRunner.sleep(1)
	device.type('cb1')
	device1.type('joe')
	device.touch(500,50,'DOWN_AND_UP')
	device1.touch(450,50,'DOWN_AND_UP')
	MonkeyRunner.sleep(1)
	device.touch(500,50,'DOWN_AND_UP')
	device1.touch(450,50,'DOWN_AND_UP')
	MonkeyRunner.sleep(2)
	device.touch(420,300,'DOWN_AND_UP')
	device1.touch(370,280,'DOWN_AND_UP')
	MonkeyRunner.sleep(3)
	device.touch(300,900,'DOWN_AND_UP')
	device1.touch(280,900,'DOWN_AND_UP')
	MonkeyRunner.sleep(70)
	device.press('KEYCODE_BACK','DOWN_AND_UP')
	device1.press('KEYCODE_BACK','DOWN_AND_UP')
	MonkeyRunner.sleep(1)
	device.press('KEYCODE_BACK','DOWN_AND_UP')
	device1.press('KEYCODE_BACK','DOWN_AND_UP')
	MonkeyRunner.sleep(1)
	device.press('KEYCODE_BACK','DOWN_AND_UP')
	device1.press('KEYCODE_BACK','DOWN_AND_UP')
	MonkeyRunner.sleep(1)
	
def execute():
	device.touch(300,840,'DOWN_AND_UP')
	device1.touch(270,820,'DOWN_AND_UP')
	MonkeyRunner.sleep(2)
	device.touch(250,920,'DOWN_AND_UP')
	device1.touch(200,910,'DOWN_AND_UP')
	MonkeyRunner.sleep(1)
	device.type('~!@#$%^&*()_+QWERTYUIOP{}|ASDFGHJKL:"ZXCVBNM<>?')	
	device.press('KEYCODE_SPACE','DOWN_AND_UP')
	device.type("`1234567890-=qwertyuiop[]\sadfghjkl;'zxcvbnm,./")
	device.type('~!@#$%^&*()_+QWERTYUIOP{}|ASDFGHJKL:"ZXCVBNM<>?')
	MonkeyRunner.sleep(1)
	device.touch(500,520,'DOWN_AND_UP')
	MonkeyRunner.sleep(30)
	if checkpic.keyCheck(device,caseName,1,1,'selfChat')==0:
		return 0
	if checkpic.keyCheck(device1,caseName,1,2,'othersChat')==0:
		return 0
	device1.touch(260,390,'DOWN_AND_UP')
	MonkeyRunner.sleep(2)
	device1.touch(390,590,'DOWN_AND_UP')
	MonkeyRunner.sleep(2)
	device1.type('~!@#$%^&*()_+QWERTYUIOP{}|ASDFGHJKL:"ZXCVBNM<>?')	
	device1.press('KEYCODE_SPACE','DOWN_AND_UP')
	device1.type("`1234567890-=qwertyuiop[]\sadfghjkl;'zxcvbnm,./")
	device1.type('~!@#$%^&*()_+QWERTYUIOP{}|ASDFGHJKL:"ZXCVBNM<>?')
	MonkeyRunner.sleep(1)
	device1.touch(450,520,'DOWN_AND_UP')
	MonkeyRunner.sleep(30)
	if checkpic.keyCheck(device,caseName,1,3,'selfChat')==0:
		return 0
	device.touch(440,130,'DOWN_AND_UP')
	device1.touch(400,120,'DOWN_AND_UP')
	MonkeyRunner.sleep(1)
	for i in range(5):
		device1.press('KEYCODE_DEL','DOWN_AND_UP')
	MonkeyRunner.sleep(1)
	device1.type('~!@#$%^&*()_+QWERTYUIOP{}|ASDFGHJKL:"ZXCVBNM<>?')	
	device1.press('KEYCODE_SPACE','DOWN_AND_UP')
	device1.type("`1234567890-=qwertyuiop[]\sadfghjkl;'zxcvbnm,./")
	device1.type('~!@#$%^&*()_+QWERTYUIOP{}|ASDFGHJKL:"ZXCVBNM<>?')
	MonkeyRunner.sleep(1)
	device1.touch(420,520,'DOWN_AND_UP')
	MonkeyRunner.sleep(30)
	if checkpic.keyCheck(device,caseName,1,4,'selfChat')==0:
		return 0
	device1.touch(500,520,'DOWN_AND_UP')
	MonkeyRunner.sleep(2)
	device1.touch(300,520,'DOWN_AND_UP')
	MonkeyRunner.sleep(1)
	device1.touch(350,590,'DOWN_AND_UP')
	MonkeyRunner.sleep(1)
	device1.touch(390,660,'DOWN_AND_UP')
	MonkeyRunner.sleep(1)
	device1.touch(440,720,'DOWN_AND_UP')
	MonkeyRunner.sleep(1)
	device1.touch(170,820,'DOWN_AND_UP')
	MonkeyRunner.sleep(30)
	if checkpic.keyCheck(device,caseName,1,5,'selfChat')==0:
		return 0
	device.touch(520,420,'DOWN_AND_UP')
	MonkeyRunner.sleep(2)
	device.touch(480,220,'DOWN_AND_UP')
	MonkeyRunner.sleep(2)
	device.touch(100,720,'DOWN_AND_UP')
	MonkeyRunner.sleep(1)
	device.touch(500,940,'DOWN_AND_UP')
	MonkeyRunner.sleep(2)
	device.touch(440,860,'DOWN_AND_UP')
	MonkeyRunner.sleep(2)
	device.touch(480,520,'DOWN_AND_UP')
	MonkeyRunner.sleep(2)
	device.touch(100,720,'DOWN_AND_UP')
	MonkeyRunner.sleep(1)
	device.touch(500,940,'DOWN_AND_UP')
	MonkeyRunner.sleep(2)
	device.touch(220,720,'DOWN_AND_UP')
	MonkeyRunner.sleep(1)
	device.drag((300,800),(300,100),0.1,1)
	MonkeyRunner.sleep(1)
	device.touch(220,720,'DOWN_AND_UP')
	MonkeyRunner.sleep(1)
	device.touch(440,860,'DOWN_AND_UP')
	MonkeyRunner.sleep(5)
	device.touch(250,920,'DOWN_AND_UP')
	MonkeyRunner.sleep(2)
	if checkpic.keyCheck(device,caseName,1,6,'selfChat')==0:
		return 0
	device1.touch(500,910,'DOWN_AND_UP')
	MonkeyRunner.sleep(2)
	device1.touch(350,170,'DOWN_AND_UP')
	MonkeyRunner.sleep(2)
	device1.touch(170,820,'DOWN_AND_UP')
	MonkeyRunner.sleep(30)
	if checkpic.keyCheck(device,caseName,1,7,'selfChat')==0:
		return 0
	device.touch(520,430,'DOWN_AND_UP')
	MonkeyRunner.sleep(2)
	device.touch(300,230,'DOWN_AND_UP')
	MonkeyRunner.sleep(1)
	device.touch(450,860,'DOWN_AND_UP')
	MonkeyRunner.sleep(2)
	device.touch(480,220,'DOWN_AND_UP')
	MonkeyRunner.sleep(2)
	device.touch(100,720,'DOWN_AND_UP')
	MonkeyRunner.sleep(1)
	device.touch(500,940,'DOWN_AND_UP')
	MonkeyRunner.sleep(2)
	device.touch(440,860,'DOWN_AND_UP')
	MonkeyRunner.sleep(2)
	device.touch(440,860,'DOWN_AND_UP')
	MonkeyRunner.sleep(5)
	if checkpic.keyCheck(device,caseName,1,8,'selfChat')==0:
		return 0
		
if __name__=='__main__':
	init()
	execute()