# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PBMsgAssignHero.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='PBMsgAssignHero.proto',
  package='',
  serialized_pb='\n\x15PBMsgAssignHero.proto\"\xe5\x05\n\x0fPBMsgAssignHero\x12\x11\n\tcityIndex\x18\x01 \x02(\x05\x12\x0b\n\x03sid\x18\x02 \x02(\x05\x12\x0b\n\x03hid\x18\x03 \x02(\x03\x12(\n\x04hero\x18\x04 \x03(\x0b\x32\x1a.PBMsgAssignHero.PBMsgHero\x1az\n\x11PBMsgSkillActived\x12\n\n\x02id\x18\x01 \x02(\x05\x12\x0f\n\x07\x61\x63tived\x18\x02 \x02(\x08\x12\n\n\x02lv\x18\x03 \x01(\x05\x12\x0c\n\x04hero\x18\x04 \x01(\x05\x12\x0c\n\x04gear\x18\x05 \x01(\x05\x12\x10\n\x08\x65\x66\x66\x65\x63tId\x18\x06 \x01(\x05\x12\x0e\n\x06\x65\x66\x66\x65\x63t\x18\x07 \x03(\t\x1a\x8c\x03\n\tPBMsgHero\x12\x12\n\nuserHeroId\x18\x01 \x02(\x03\x12\x30\n\x06status\x18\x02 \x01(\x0e\x32 .PBMsgAssignHero.PBMsgHeroStatus\x12\x0e\n\x06heroId\x18\x03 \x01(\x05\x12\r\n\x05level\x18\x04 \x01(\x05\x12\x0e\n\x06renown\x18\x05 \x01(\x05\x12\x12\n\nnextRenown\x18\x06 \x01(\x05\x12\x0e\n\x06\x61ttack\x18\x07 \x01(\x05\x12\n\n\x02hp\x18\x08 \x01(\x05\x12\x0c\n\x04load\x18\t \x01(\x05\x12\x31\n\x05skill\x18\n \x03(\x0b\x32\".PBMsgAssignHero.PBMsgSkillActived\x12\x30\n\x04\x66\x61te\x18\x0b \x03(\x0b\x32\".PBMsgAssignHero.PBMsgSkillActived\x12\r\n\x05might\x18\x0c \x01(\x05\x12\x12\n\nmaxExplore\x18\r \x01(\x05\x12\x10\n\x08\x65xplored\x18\x0e \x01(\x05\x12\x11\n\tsleepTime\x18\x0f \x01(\x05\x12\x11\n\tcityIndex\x18\x10 \x01(\x05\x12\x0c\n\x04slot\x18\x11 \x01(\x05\"p\n\x0fPBMsgHeroStatus\x12\x0c\n\x08UNLOCKED\x10\x01\x12\x16\n\x12IN_CITY_DO_NOTHING\x10\x02\x12\x14\n\x10IN_CITY_IN_MARCH\x10\x03\x12\x11\n\rIN_CITY_SLEEP\x10\x04\x12\x0e\n\nIN_NO_CITY\x10\x05')



_PBMSGASSIGNHERO_PBMSGHEROSTATUS = _descriptor.EnumDescriptor(
  name='PBMsgHeroStatus',
  full_name='PBMsgAssignHero.PBMsgHeroStatus',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNLOCKED', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='IN_CITY_DO_NOTHING', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='IN_CITY_IN_MARCH', index=2, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='IN_CITY_SLEEP', index=3, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='IN_NO_CITY', index=4, number=5,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=655,
  serialized_end=767,
)


_PBMSGASSIGNHERO_PBMSGSKILLACTIVED = _descriptor.Descriptor(
  name='PBMsgSkillActived',
  full_name='PBMsgAssignHero.PBMsgSkillActived',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='PBMsgAssignHero.PBMsgSkillActived.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='actived', full_name='PBMsgAssignHero.PBMsgSkillActived.actived', index=1,
      number=2, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lv', full_name='PBMsgAssignHero.PBMsgSkillActived.lv', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hero', full_name='PBMsgAssignHero.PBMsgSkillActived.hero', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gear', full_name='PBMsgAssignHero.PBMsgSkillActived.gear', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='effectId', full_name='PBMsgAssignHero.PBMsgSkillActived.effectId', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='effect', full_name='PBMsgAssignHero.PBMsgSkillActived.effect', index=6,
      number=7, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=132,
  serialized_end=254,
)

_PBMSGASSIGNHERO_PBMSGHERO = _descriptor.Descriptor(
  name='PBMsgHero',
  full_name='PBMsgAssignHero.PBMsgHero',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='userHeroId', full_name='PBMsgAssignHero.PBMsgHero.userHeroId', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='status', full_name='PBMsgAssignHero.PBMsgHero.status', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='heroId', full_name='PBMsgAssignHero.PBMsgHero.heroId', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='level', full_name='PBMsgAssignHero.PBMsgHero.level', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='renown', full_name='PBMsgAssignHero.PBMsgHero.renown', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nextRenown', full_name='PBMsgAssignHero.PBMsgHero.nextRenown', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='attack', full_name='PBMsgAssignHero.PBMsgHero.attack', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hp', full_name='PBMsgAssignHero.PBMsgHero.hp', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='load', full_name='PBMsgAssignHero.PBMsgHero.load', index=8,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='skill', full_name='PBMsgAssignHero.PBMsgHero.skill', index=9,
      number=10, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fate', full_name='PBMsgAssignHero.PBMsgHero.fate', index=10,
      number=11, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='might', full_name='PBMsgAssignHero.PBMsgHero.might', index=11,
      number=12, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='maxExplore', full_name='PBMsgAssignHero.PBMsgHero.maxExplore', index=12,
      number=13, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='explored', full_name='PBMsgAssignHero.PBMsgHero.explored', index=13,
      number=14, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sleepTime', full_name='PBMsgAssignHero.PBMsgHero.sleepTime', index=14,
      number=15, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cityIndex', full_name='PBMsgAssignHero.PBMsgHero.cityIndex', index=15,
      number=16, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='slot', full_name='PBMsgAssignHero.PBMsgHero.slot', index=16,
      number=17, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=257,
  serialized_end=653,
)

_PBMSGASSIGNHERO = _descriptor.Descriptor(
  name='PBMsgAssignHero',
  full_name='PBMsgAssignHero',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cityIndex', full_name='PBMsgAssignHero.cityIndex', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sid', full_name='PBMsgAssignHero.sid', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hid', full_name='PBMsgAssignHero.hid', index=2,
      number=3, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hero', full_name='PBMsgAssignHero.hero', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_PBMSGASSIGNHERO_PBMSGSKILLACTIVED, _PBMSGASSIGNHERO_PBMSGHERO, ],
  enum_types=[
    _PBMSGASSIGNHERO_PBMSGHEROSTATUS,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=26,
  serialized_end=767,
)

_PBMSGASSIGNHERO_PBMSGSKILLACTIVED.containing_type = _PBMSGASSIGNHERO;
_PBMSGASSIGNHERO_PBMSGHERO.fields_by_name['status'].enum_type = _PBMSGASSIGNHERO_PBMSGHEROSTATUS
_PBMSGASSIGNHERO_PBMSGHERO.fields_by_name['skill'].message_type = _PBMSGASSIGNHERO_PBMSGSKILLACTIVED
_PBMSGASSIGNHERO_PBMSGHERO.fields_by_name['fate'].message_type = _PBMSGASSIGNHERO_PBMSGSKILLACTIVED
_PBMSGASSIGNHERO_PBMSGHERO.containing_type = _PBMSGASSIGNHERO;
_PBMSGASSIGNHERO.fields_by_name['hero'].message_type = _PBMSGASSIGNHERO_PBMSGHERO
_PBMSGASSIGNHERO_PBMSGHEROSTATUS.containing_type = _PBMSGASSIGNHERO;
DESCRIPTOR.message_types_by_name['PBMsgAssignHero'] = _PBMSGASSIGNHERO

class PBMsgAssignHero(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType

  class PBMsgSkillActived(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _PBMSGASSIGNHERO_PBMSGSKILLACTIVED

    # @@protoc_insertion_point(class_scope:PBMsgAssignHero.PBMsgSkillActived)

  class PBMsgHero(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _PBMSGASSIGNHERO_PBMSGHERO

    # @@protoc_insertion_point(class_scope:PBMsgAssignHero.PBMsgHero)
  DESCRIPTOR = _PBMSGASSIGNHERO

  # @@protoc_insertion_point(class_scope:PBMsgAssignHero)


# @@protoc_insertion_point(module_scope)
