# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PBMsgReqPve.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='PBMsgReqPve.proto',
  package='',
  serialized_pb='\n\x11PBMsgReqPve.proto\"n\n\x0bPBMsgReqPve\x12\x0c\n\x04type\x18\x01 \x01(\x05\x12\x10\n\x08knightId\x18\x02 \x01(\x05\x12\x0e\n\x06\x63ityId\x18\x03 \x01(\x05\x12\x0f\n\x07marchId\x18\x04 \x01(\x05\x12\x0f\n\x07levelId\x18\x05 \x01(\x05\x12\r\n\x05units\x18\x06 \x03(\x05')




_PBMSGREQPVE = _descriptor.Descriptor(
  name='PBMsgReqPve',
  full_name='PBMsgReqPve',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='PBMsgReqPve.type', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='knightId', full_name='PBMsgReqPve.knightId', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cityId', full_name='PBMsgReqPve.cityId', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='marchId', full_name='PBMsgReqPve.marchId', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='levelId', full_name='PBMsgReqPve.levelId', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='units', full_name='PBMsgReqPve.units', index=5,
      number=6, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=21,
  serialized_end=131,
)

DESCRIPTOR.message_types_by_name['PBMsgReqPve'] = _PBMSGREQPVE

class PBMsgReqPve(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PBMSGREQPVE

  # @@protoc_insertion_point(class_scope:PBMsgReqPve)


# @@protoc_insertion_point(module_scope)
