# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PBMsgPveInfo.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='PBMsgPveInfo.proto',
  package='',
  serialized_pb='\n\x12PBMsgPveInfo.proto\"\x9c\x04\n\x0cPBMsgPveInfo\x12\x12\n\ntotalScore\x18\x01 \x01(\x05\x12\x12\n\ntotalStars\x18\x02 \x01(\x05\x12\x32\n\tlevelInfo\x18\x03 \x03(\x0b\x32\x1f.PBMsgPveInfo.PBMsgPveLevelInfo\x12\x13\n\x0bstaminaInfo\x18\x04 \x01(\x0c\x12\x12\n\nresultInfo\x18\x05 \x01(\x0c\x12\x11\n\tmarchInfo\x18\x06 \x01(\x0c\x12:\n\rhidenBossInfo\x18\x07 \x03(\x0b\x32#.PBMsgPveInfo.PBMsgPveHidenBossInfo\x1a\xf9\x01\n\x11PBMsgPveLevelInfo\x12\x0f\n\x07levelID\x18\x01 \x02(\x05\x12\x14\n\x0chighestScore\x18\x02 \x01(\x05\x12\x13\n\x0bhighestStar\x18\x03 \x01(\x05\x12\x14\n\x0chighestSpeed\x18\x04 \x01(\x05\x12\x17\n\x0fhighestVitality\x18\x05 \x01(\x05\x12\x16\n\x0ehighestTactics\x18\x06 \x01(\x05\x12\x11\n\tlastScore\x18\x07 \x01(\x05\x12\x10\n\x08lastStar\x18\x08 \x01(\x05\x12\x11\n\tlastSpeed\x18\t \x01(\x05\x12\x14\n\x0clastVitality\x18\n \x01(\x05\x12\x13\n\x0blastTactics\x18\x0b \x01(\x05\x1a<\n\x15PBMsgPveHidenBossInfo\x12\x0f\n\x07levelID\x18\x01 \x02(\x05\x12\x12\n\nactiveTime\x18\x02 \x01(\x03')




_PBMSGPVEINFO_PBMSGPVELEVELINFO = _descriptor.Descriptor(
  name='PBMsgPveLevelInfo',
  full_name='PBMsgPveInfo.PBMsgPveLevelInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='levelID', full_name='PBMsgPveInfo.PBMsgPveLevelInfo.levelID', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='highestScore', full_name='PBMsgPveInfo.PBMsgPveLevelInfo.highestScore', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='highestStar', full_name='PBMsgPveInfo.PBMsgPveLevelInfo.highestStar', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='highestSpeed', full_name='PBMsgPveInfo.PBMsgPveLevelInfo.highestSpeed', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='highestVitality', full_name='PBMsgPveInfo.PBMsgPveLevelInfo.highestVitality', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='highestTactics', full_name='PBMsgPveInfo.PBMsgPveLevelInfo.highestTactics', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lastScore', full_name='PBMsgPveInfo.PBMsgPveLevelInfo.lastScore', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lastStar', full_name='PBMsgPveInfo.PBMsgPveLevelInfo.lastStar', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lastSpeed', full_name='PBMsgPveInfo.PBMsgPveLevelInfo.lastSpeed', index=8,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lastVitality', full_name='PBMsgPveInfo.PBMsgPveLevelInfo.lastVitality', index=9,
      number=10, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lastTactics', full_name='PBMsgPveInfo.PBMsgPveLevelInfo.lastTactics', index=10,
      number=11, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=252,
  serialized_end=501,
)

_PBMSGPVEINFO_PBMSGPVEHIDENBOSSINFO = _descriptor.Descriptor(
  name='PBMsgPveHidenBossInfo',
  full_name='PBMsgPveInfo.PBMsgPveHidenBossInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='levelID', full_name='PBMsgPveInfo.PBMsgPveHidenBossInfo.levelID', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='activeTime', full_name='PBMsgPveInfo.PBMsgPveHidenBossInfo.activeTime', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=503,
  serialized_end=563,
)

_PBMSGPVEINFO = _descriptor.Descriptor(
  name='PBMsgPveInfo',
  full_name='PBMsgPveInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='totalScore', full_name='PBMsgPveInfo.totalScore', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='totalStars', full_name='PBMsgPveInfo.totalStars', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='levelInfo', full_name='PBMsgPveInfo.levelInfo', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='staminaInfo', full_name='PBMsgPveInfo.staminaInfo', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='resultInfo', full_name='PBMsgPveInfo.resultInfo', index=4,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='marchInfo', full_name='PBMsgPveInfo.marchInfo', index=5,
      number=6, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hidenBossInfo', full_name='PBMsgPveInfo.hidenBossInfo', index=6,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_PBMSGPVEINFO_PBMSGPVELEVELINFO, _PBMSGPVEINFO_PBMSGPVEHIDENBOSSINFO, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=23,
  serialized_end=563,
)

_PBMSGPVEINFO_PBMSGPVELEVELINFO.containing_type = _PBMSGPVEINFO;
_PBMSGPVEINFO_PBMSGPVEHIDENBOSSINFO.containing_type = _PBMSGPVEINFO;
_PBMSGPVEINFO.fields_by_name['levelInfo'].message_type = _PBMSGPVEINFO_PBMSGPVELEVELINFO
_PBMSGPVEINFO.fields_by_name['hidenBossInfo'].message_type = _PBMSGPVEINFO_PBMSGPVEHIDENBOSSINFO
DESCRIPTOR.message_types_by_name['PBMsgPveInfo'] = _PBMSGPVEINFO

class PBMsgPveInfo(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType

  class PBMsgPveLevelInfo(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _PBMSGPVEINFO_PBMSGPVELEVELINFO

    # @@protoc_insertion_point(class_scope:PBMsgPveInfo.PBMsgPveLevelInfo)

  class PBMsgPveHidenBossInfo(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _PBMSGPVEINFO_PBMSGPVEHIDENBOSSINFO

    # @@protoc_insertion_point(class_scope:PBMsgPveInfo.PBMsgPveHidenBossInfo)
  DESCRIPTOR = _PBMSGPVEINFO

  # @@protoc_insertion_point(class_scope:PBMsgPveInfo)


# @@protoc_insertion_point(module_scope)
