# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PBMsgReqHeroHouseList.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='PBMsgReqHeroHouseList.proto',
  package='',
  serialized_pb='\n\x1bPBMsgReqHeroHouseList.proto\"$\n\x15PBMsgReqHeroHouseList\x12\x0b\n\x03\x63id\x18\x01 \x02(\x03')




_PBMSGREQHEROHOUSELIST = _descriptor.Descriptor(
  name='PBMsgReqHeroHouseList',
  full_name='PBMsgReqHeroHouseList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cid', full_name='PBMsgReqHeroHouseList.cid', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=31,
  serialized_end=67,
)

DESCRIPTOR.message_types_by_name['PBMsgReqHeroHouseList'] = _PBMSGREQHEROHOUSELIST

class PBMsgReqHeroHouseList(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PBMSGREQHEROHOUSELIST

  # @@protoc_insertion_point(class_scope:PBMsgReqHeroHouseList)


# @@protoc_insertion_point(module_scope)
