# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PBMsgHeroItemList.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='PBMsgHeroItemList.proto',
  package='',
  serialized_pb='\n\x17PBMsgHeroItemList.proto\"\x88\x01\n\x11PBMsgHeroItemList\x12\x32\n\x08heroItem\x18\x01 \x03(\x0b\x32 .PBMsgHeroItemList.PBMsgHeroItem\x1a?\n\rPBMsgHeroItem\x12\x0e\n\x06itemId\x18\x01 \x02(\x05\x12\x11\n\taddRenown\x18\x02 \x02(\x05\x12\x0b\n\x03own\x18\x03 \x02(\x05')




_PBMSGHEROITEMLIST_PBMSGHEROITEM = _descriptor.Descriptor(
  name='PBMsgHeroItem',
  full_name='PBMsgHeroItemList.PBMsgHeroItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='itemId', full_name='PBMsgHeroItemList.PBMsgHeroItem.itemId', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='addRenown', full_name='PBMsgHeroItemList.PBMsgHeroItem.addRenown', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='own', full_name='PBMsgHeroItemList.PBMsgHeroItem.own', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=101,
  serialized_end=164,
)

_PBMSGHEROITEMLIST = _descriptor.Descriptor(
  name='PBMsgHeroItemList',
  full_name='PBMsgHeroItemList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='heroItem', full_name='PBMsgHeroItemList.heroItem', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_PBMSGHEROITEMLIST_PBMSGHEROITEM, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=28,
  serialized_end=164,
)

_PBMSGHEROITEMLIST_PBMSGHEROITEM.containing_type = _PBMSGHEROITEMLIST;
_PBMSGHEROITEMLIST.fields_by_name['heroItem'].message_type = _PBMSGHEROITEMLIST_PBMSGHEROITEM
DESCRIPTOR.message_types_by_name['PBMsgHeroItemList'] = _PBMSGHEROITEMLIST

class PBMsgHeroItemList(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType

  class PBMsgHeroItem(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _PBMSGHEROITEMLIST_PBMSGHEROITEM

    # @@protoc_insertion_point(class_scope:PBMsgHeroItemList.PBMsgHeroItem)
  DESCRIPTOR = _PBMSGHEROITEMLIST

  # @@protoc_insertion_point(class_scope:PBMsgHeroItemList)


# @@protoc_insertion_point(module_scope)
