# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PBMsgUpdateSeed.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='PBMsgUpdateSeed.proto',
  package='',
  serialized_pb='\n\x15PBMsgUpdateSeed.proto\"\xa1\x01\n\x0fPBMsgUpdateSeed\x12\x0e\n\x06pveMd5\x18\x01 \x01(\t\x12)\n\x07pveData\x18\x02 \x01(\x0b\x32\x18.PBMsgUpdateSeed.PveData\x12\x0f\n\x07heroMd5\x18\x03 \x01(\t\x12+\n\x08heroData\x18\x04 \x01(\x0b\x32\x19.PBMsgUpdateSeed.HeroData\x1a\t\n\x07PveData\x1a\n\n\x08HeroData')




_PBMSGUPDATESEED_PVEDATA = _descriptor.Descriptor(
  name='PveData',
  full_name='PBMsgUpdateSeed.PveData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=166,
  serialized_end=175,
)

_PBMSGUPDATESEED_HERODATA = _descriptor.Descriptor(
  name='HeroData',
  full_name='PBMsgUpdateSeed.HeroData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=177,
  serialized_end=187,
)

_PBMSGUPDATESEED = _descriptor.Descriptor(
  name='PBMsgUpdateSeed',
  full_name='PBMsgUpdateSeed',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pveMd5', full_name='PBMsgUpdateSeed.pveMd5', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pveData', full_name='PBMsgUpdateSeed.pveData', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='heroMd5', full_name='PBMsgUpdateSeed.heroMd5', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='heroData', full_name='PBMsgUpdateSeed.heroData', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_PBMSGUPDATESEED_PVEDATA, _PBMSGUPDATESEED_HERODATA, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=26,
  serialized_end=187,
)

_PBMSGUPDATESEED_PVEDATA.containing_type = _PBMSGUPDATESEED;
_PBMSGUPDATESEED_HERODATA.containing_type = _PBMSGUPDATESEED;
_PBMSGUPDATESEED.fields_by_name['pveData'].message_type = _PBMSGUPDATESEED_PVEDATA
_PBMSGUPDATESEED.fields_by_name['heroData'].message_type = _PBMSGUPDATESEED_HERODATA
DESCRIPTOR.message_types_by_name['PBMsgUpdateSeed'] = _PBMSGUPDATESEED

class PBMsgUpdateSeed(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType

  class PveData(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _PBMSGUPDATESEED_PVEDATA

    # @@protoc_insertion_point(class_scope:PBMsgUpdateSeed.PveData)

  class HeroData(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _PBMSGUPDATESEED_HERODATA

    # @@protoc_insertion_point(class_scope:PBMsgUpdateSeed.HeroData)
  DESCRIPTOR = _PBMSGUPDATESEED

  # @@protoc_insertion_point(class_scope:PBMsgUpdateSeed)


# @@protoc_insertion_point(module_scope)
