# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PBMsgReqAssignHero.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='PBMsgReqAssignHero.proto',
  package='',
  serialized_pb='\n\x18PBMsgReqAssignHero.proto\";\n\x12PBMsgReqAssignHero\x12\x0b\n\x03\x63id\x18\x01 \x02(\x03\x12\x0b\n\x03hid\x18\x02 \x02(\x03\x12\x0b\n\x03sid\x18\x03 \x02(\x05')




_PBMSGREQASSIGNHERO = _descriptor.Descriptor(
  name='PBMsgReqAssignHero',
  full_name='PBMsgReqAssignHero',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cid', full_name='PBMsgReqAssignHero.cid', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hid', full_name='PBMsgReqAssignHero.hid', index=1,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sid', full_name='PBMsgReqAssignHero.sid', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=28,
  serialized_end=87,
)

DESCRIPTOR.message_types_by_name['PBMsgReqAssignHero'] = _PBMSGREQASSIGNHERO

class PBMsgReqAssignHero(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PBMSGREQASSIGNHERO

  # @@protoc_insertion_point(class_scope:PBMsgReqAssignHero)


# @@protoc_insertion_point(module_scope)
