# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PBMsgPveResultInfo.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='PBMsgPveResultInfo.proto',
  package='',
  serialized_pb='\n\x18PBMsgPveResultInfo.proto\"\x95\x01\n\x12PBMsgPveResultInfo\x12\x0f\n\x07levelID\x18\x01 \x02(\x05\x12\r\n\x05score\x18\x02 \x01(\x05\x12\x0c\n\x04star\x18\x03 \x01(\x05\x12\r\n\x05speed\x18\x04 \x01(\x05\x12\x10\n\x08vitality\x18\x05 \x01(\x05\x12\x0f\n\x07tactics\x18\x06 \x01(\x05\x12\x11\n\tisHighest\x18\x07 \x01(\x08\x12\x0c\n\x04item\x18\x08 \x03(\x05')




_PBMSGPVERESULTINFO = _descriptor.Descriptor(
  name='PBMsgPveResultInfo',
  full_name='PBMsgPveResultInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='levelID', full_name='PBMsgPveResultInfo.levelID', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='score', full_name='PBMsgPveResultInfo.score', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='star', full_name='PBMsgPveResultInfo.star', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='speed', full_name='PBMsgPveResultInfo.speed', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='vitality', full_name='PBMsgPveResultInfo.vitality', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tactics', full_name='PBMsgPveResultInfo.tactics', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='isHighest', full_name='PBMsgPveResultInfo.isHighest', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='item', full_name='PBMsgPveResultInfo.item', index=7,
      number=8, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=29,
  serialized_end=178,
)

DESCRIPTOR.message_types_by_name['PBMsgPveResultInfo'] = _PBMSGPVERESULTINFO

class PBMsgPveResultInfo(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PBMSGPVERESULTINFO

  # @@protoc_insertion_point(class_scope:PBMsgPveResultInfo)


# @@protoc_insertion_point(module_scope)
