# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PBMsgReqBoostHero.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='PBMsgReqBoostHero.proto',
  package='',
  serialized_pb='\n\x17PBMsgReqBoostHero.proto\"-\n\x11PBMsgReqBoostHero\x12\x0b\n\x03hid\x18\x01 \x02(\x03\x12\x0b\n\x03iid\x18\x02 \x02(\x05')




_PBMSGREQBOOSTHERO = _descriptor.Descriptor(
  name='PBMsgReqBoostHero',
  full_name='PBMsgReqBoostHero',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='hid', full_name='PBMsgReqBoostHero.hid', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='iid', full_name='PBMsgReqBoostHero.iid', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=27,
  serialized_end=72,
)

DESCRIPTOR.message_types_by_name['PBMsgReqBoostHero'] = _PBMSGREQBOOSTHERO

class PBMsgReqBoostHero(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PBMSGREQBOOSTHERO

  # @@protoc_insertion_point(class_scope:PBMsgReqBoostHero)


# @@protoc_insertion_point(module_scope)
