# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PBMsgReqPveMarch.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='PBMsgReqPveMarch.proto',
  package='',
  serialized_pb='\n\x16PBMsgReqPveMarch.proto\"\x92\x03\n\x10PBMsgReqPveMarch\x12\x10\n\x08knightId\x18\x01 \x01(\x05\x12\x0e\n\x06\x63ityId\x18\x02 \x01(\x05\x12\x0f\n\x07marchId\x18\x03 \x01(\x05\x12\x0f\n\x07levelId\x18\x04 \x01(\x05\x12\n\n\x02u1\x18\x05 \x01(\x05\x12\n\n\x02u2\x18\x06 \x01(\x05\x12\n\n\x02u3\x18\x07 \x01(\x05\x12\n\n\x02u4\x18\x08 \x01(\x05\x12\n\n\x02u5\x18\t \x01(\x05\x12\n\n\x02u6\x18\n \x01(\x05\x12\n\n\x02u7\x18\x0b \x01(\x05\x12\n\n\x02u8\x18\x0c \x01(\x05\x12\n\n\x02u9\x18\r \x01(\x05\x12\x0b\n\x03u10\x18\x0e \x01(\x05\x12\x0b\n\x03u11\x18\x0f \x01(\x05\x12\x0b\n\x03u12\x18\x10 \x01(\x05\x12\x0b\n\x03u13\x18\x11 \x01(\x05\x12\x0b\n\x03u14\x18\x12 \x01(\x05\x12\x0b\n\x03u15\x18\x13 \x01(\x05\x12\x0b\n\x03u16\x18\x14 \x01(\x05\x12\x0b\n\x03u17\x18\x15 \x01(\x05\x12\x0b\n\x03u18\x18\x16 \x01(\x05\x12\x0b\n\x03u19\x18\x17 \x01(\x05\x12\x0b\n\x03u20\x18\x18 \x01(\x05\x12\x0b\n\x03u21\x18\x19 \x01(\x05\x12\x0b\n\x03u22\x18\x1a \x01(\x05\x12\x0b\n\x03u23\x18\x1b \x01(\x05\x12\x0b\n\x03u24\x18\x1c \x01(\x05\x12\x0b\n\x03u25\x18\x1d \x01(\x05')




_PBMSGREQPVEMARCH = _descriptor.Descriptor(
  name='PBMsgReqPveMarch',
  full_name='PBMsgReqPveMarch',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='knightId', full_name='PBMsgReqPveMarch.knightId', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cityId', full_name='PBMsgReqPveMarch.cityId', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='marchId', full_name='PBMsgReqPveMarch.marchId', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='levelId', full_name='PBMsgReqPveMarch.levelId', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='u1', full_name='PBMsgReqPveMarch.u1', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='u2', full_name='PBMsgReqPveMarch.u2', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='u3', full_name='PBMsgReqPveMarch.u3', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='u4', full_name='PBMsgReqPveMarch.u4', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='u5', full_name='PBMsgReqPveMarch.u5', index=8,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='u6', full_name='PBMsgReqPveMarch.u6', index=9,
      number=10, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='u7', full_name='PBMsgReqPveMarch.u7', index=10,
      number=11, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='u8', full_name='PBMsgReqPveMarch.u8', index=11,
      number=12, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='u9', full_name='PBMsgReqPveMarch.u9', index=12,
      number=13, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='u10', full_name='PBMsgReqPveMarch.u10', index=13,
      number=14, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='u11', full_name='PBMsgReqPveMarch.u11', index=14,
      number=15, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='u12', full_name='PBMsgReqPveMarch.u12', index=15,
      number=16, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='u13', full_name='PBMsgReqPveMarch.u13', index=16,
      number=17, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='u14', full_name='PBMsgReqPveMarch.u14', index=17,
      number=18, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='u15', full_name='PBMsgReqPveMarch.u15', index=18,
      number=19, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='u16', full_name='PBMsgReqPveMarch.u16', index=19,
      number=20, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='u17', full_name='PBMsgReqPveMarch.u17', index=20,
      number=21, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='u18', full_name='PBMsgReqPveMarch.u18', index=21,
      number=22, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='u19', full_name='PBMsgReqPveMarch.u19', index=22,
      number=23, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='u20', full_name='PBMsgReqPveMarch.u20', index=23,
      number=24, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='u21', full_name='PBMsgReqPveMarch.u21', index=24,
      number=25, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='u22', full_name='PBMsgReqPveMarch.u22', index=25,
      number=26, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='u23', full_name='PBMsgReqPveMarch.u23', index=26,
      number=27, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='u24', full_name='PBMsgReqPveMarch.u24', index=27,
      number=28, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='u25', full_name='PBMsgReqPveMarch.u25', index=28,
      number=29, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=27,
  serialized_end=429,
)

DESCRIPTOR.message_types_by_name['PBMsgReqPveMarch'] = _PBMSGREQPVEMARCH

class PBMsgReqPveMarch(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PBMSGREQPVEMARCH

  # @@protoc_insertion_point(class_scope:PBMsgReqPveMarch)


# @@protoc_insertion_point(module_scope)
