# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PBMsgReqGds.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='PBMsgReqGds.proto',
  package='',
  serialized_pb='\n\x11PBMsgReqGds.proto\"=\n\x0bPBMsgReqGds\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x0f\n\x07worldId\x18\x02 \x01(\x05\x12\x0f\n\x07version\x18\x03 \x01(\x05')




_PBMSGREQGDS = _descriptor.Descriptor(
  name='PBMsgReqGds',
  full_name='PBMsgReqGds',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='PBMsgReqGds.type', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='worldId', full_name='PBMsgReqGds.worldId', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='version', full_name='PBMsgReqGds.version', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=21,
  serialized_end=82,
)

DESCRIPTOR.message_types_by_name['PBMsgReqGds'] = _PBMSGREQGDS

class PBMsgReqGds(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PBMSGREQGDS

  # @@protoc_insertion_point(class_scope:PBMsgReqGds)


# @@protoc_insertion_point(module_scope)
