# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PBMsgPveMarchInfo.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='PBMsgPveMarchInfo.proto',
  package='',
  serialized_pb='\n\x17PBMsgPveMarchInfo.proto\"b\n\x11PBMsgPveMarchInfo\x12\x0f\n\x07marchID\x18\x01 \x02(\x05\x12\x0f\n\x07levelID\x18\x02 \x01(\x05\x12\x11\n\tmarchTime\x18\x03 \x01(\x03\x12\x18\n\x10hidenBossLevelID\x18\x04 \x01(\x05')




_PBMSGPVEMARCHINFO = _descriptor.Descriptor(
  name='PBMsgPveMarchInfo',
  full_name='PBMsgPveMarchInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='marchID', full_name='PBMsgPveMarchInfo.marchID', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='levelID', full_name='PBMsgPveMarchInfo.levelID', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='marchTime', full_name='PBMsgPveMarchInfo.marchTime', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hidenBossLevelID', full_name='PBMsgPveMarchInfo.hidenBossLevelID', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=27,
  serialized_end=125,
)

DESCRIPTOR.message_types_by_name['PBMsgPveMarchInfo'] = _PBMSGPVEMARCHINFO

class PBMsgPveMarchInfo(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PBMSGPVEMARCHINFO

  # @@protoc_insertion_point(class_scope:PBMsgPveMarchInfo)


# @@protoc_insertion_point(module_scope)
