# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PBMsgPveStaminaInfo.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='PBMsgPveStaminaInfo.proto',
  package='',
  serialized_pb='\n\x19PBMsgPveStaminaInfo.proto\"3\n\x13PBMsgPveStaminaInfo\x12\x0e\n\x06\x65nergy\x18\x01 \x01(\x05\x12\x0c\n\x04time\x18\x02 \x01(\x03')




_PBMSGPVESTAMINAINFO = _descriptor.Descriptor(
  name='PBMsgPveStaminaInfo',
  full_name='PBMsgPveStaminaInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='energy', full_name='PBMsgPveStaminaInfo.energy', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='time', full_name='PBMsgPveStaminaInfo.time', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=29,
  serialized_end=80,
)

DESCRIPTOR.message_types_by_name['PBMsgPveStaminaInfo'] = _PBMSGPVESTAMINAINFO

class PBMsgPveStaminaInfo(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PBMSGPVESTAMINAINFO

  # @@protoc_insertion_point(class_scope:PBMsgPveStaminaInfo)


# @@protoc_insertion_point(module_scope)
