# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PBMsgHeroHouseList.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='PBMsgHeroHouseList.proto',
  package='',
  serialized_pb='\n\x18PBMsgHeroHouseList.proto\"\x8c\x06\n\x12PBMsgHeroHouseList\x12\x16\n\x0eheroHouseSlots\x18\x01 \x02(\x05\x12\x13\n\x0bopennedSlot\x18\x02 \x02(\x05\x12\x16\n\x0eunlockSlotDesc\x18\x03 \x03(\x05\x12+\n\x04hero\x18\x04 \x03(\x0b\x32\x1d.PBMsgHeroHouseList.PBMsgHero\x1az\n\x11PBMsgSkillActived\x12\n\n\x02id\x18\x01 \x02(\x05\x12\x0f\n\x07\x61\x63tived\x18\x02 \x02(\x08\x12\n\n\x02lv\x18\x03 \x01(\x05\x12\x0c\n\x04hero\x18\x04 \x01(\x05\x12\x0c\n\x04gear\x18\x05 \x01(\x05\x12\x10\n\x08\x65\x66\x66\x65\x63tId\x18\x06 \x02(\x05\x12\x0e\n\x06\x65\x66\x66\x65\x63t\x18\x07 \x03(\t\x1a\x95\x03\n\tPBMsgHero\x12\x12\n\nuserHeroId\x18\x01 \x02(\x03\x12\x33\n\x06status\x18\x02 \x02(\x0e\x32#.PBMsgHeroHouseList.PBMsgHeroStatus\x12\x0e\n\x06heroId\x18\x03 \x02(\x05\x12\r\n\x05level\x18\x04 \x02(\x05\x12\x0e\n\x06renown\x18\x05 \x02(\x05\x12\x12\n\nnextRenown\x18\x06 \x02(\x05\x12\x0e\n\x06\x61ttack\x18\x07 \x02(\x05\x12\n\n\x02hp\x18\x08 \x02(\x05\x12\x0c\n\x04load\x18\t \x02(\x05\x12\x34\n\x05skill\x18\n \x03(\x0b\x32%.PBMsgHeroHouseList.PBMsgSkillActived\x12\x33\n\x04\x66\x61te\x18\x0b \x03(\x0b\x32%.PBMsgHeroHouseList.PBMsgSkillActived\x12\r\n\x05might\x18\x0c \x02(\x05\x12\x12\n\nmaxExplore\x18\r \x02(\x05\x12\x10\n\x08\x65xplored\x18\x0e \x02(\x05\x12\x11\n\tsleepTime\x18\x0f \x02(\x05\x12\x11\n\tcityIndex\x18\x10 \x02(\x05\x12\x0c\n\x04slot\x18\x11 \x02(\x05\"p\n\x0fPBMsgHeroStatus\x12\x0c\n\x08UNLOCKED\x10\x01\x12\x16\n\x12IN_CITY_DO_NOTHING\x10\x02\x12\x14\n\x10IN_CITY_IN_MARCH\x10\x03\x12\x11\n\rIN_CITY_SLEEP\x10\x04\x12\x0e\n\nIN_NO_CITY\x10\x05')



_PBMSGHEROHOUSELIST_PBMSGHEROSTATUS = _descriptor.EnumDescriptor(
  name='PBMsgHeroStatus',
  full_name='PBMsgHeroHouseList.PBMsgHeroStatus',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNLOCKED', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='IN_CITY_DO_NOTHING', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='IN_CITY_IN_MARCH', index=2, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='IN_CITY_SLEEP', index=3, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='IN_NO_CITY', index=4, number=5,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=697,
  serialized_end=809,
)


_PBMSGHEROHOUSELIST_PBMSGSKILLACTIVED = _descriptor.Descriptor(
  name='PBMsgSkillActived',
  full_name='PBMsgHeroHouseList.PBMsgSkillActived',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='PBMsgHeroHouseList.PBMsgSkillActived.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='actived', full_name='PBMsgHeroHouseList.PBMsgSkillActived.actived', index=1,
      number=2, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lv', full_name='PBMsgHeroHouseList.PBMsgSkillActived.lv', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hero', full_name='PBMsgHeroHouseList.PBMsgSkillActived.hero', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gear', full_name='PBMsgHeroHouseList.PBMsgSkillActived.gear', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='effectId', full_name='PBMsgHeroHouseList.PBMsgSkillActived.effectId', index=5,
      number=6, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='effect', full_name='PBMsgHeroHouseList.PBMsgSkillActived.effect', index=6,
      number=7, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=165,
  serialized_end=287,
)

_PBMSGHEROHOUSELIST_PBMSGHERO = _descriptor.Descriptor(
  name='PBMsgHero',
  full_name='PBMsgHeroHouseList.PBMsgHero',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='userHeroId', full_name='PBMsgHeroHouseList.PBMsgHero.userHeroId', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='status', full_name='PBMsgHeroHouseList.PBMsgHero.status', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='heroId', full_name='PBMsgHeroHouseList.PBMsgHero.heroId', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='level', full_name='PBMsgHeroHouseList.PBMsgHero.level', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='renown', full_name='PBMsgHeroHouseList.PBMsgHero.renown', index=4,
      number=5, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nextRenown', full_name='PBMsgHeroHouseList.PBMsgHero.nextRenown', index=5,
      number=6, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='attack', full_name='PBMsgHeroHouseList.PBMsgHero.attack', index=6,
      number=7, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hp', full_name='PBMsgHeroHouseList.PBMsgHero.hp', index=7,
      number=8, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='load', full_name='PBMsgHeroHouseList.PBMsgHero.load', index=8,
      number=9, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='skill', full_name='PBMsgHeroHouseList.PBMsgHero.skill', index=9,
      number=10, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fate', full_name='PBMsgHeroHouseList.PBMsgHero.fate', index=10,
      number=11, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='might', full_name='PBMsgHeroHouseList.PBMsgHero.might', index=11,
      number=12, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='maxExplore', full_name='PBMsgHeroHouseList.PBMsgHero.maxExplore', index=12,
      number=13, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='explored', full_name='PBMsgHeroHouseList.PBMsgHero.explored', index=13,
      number=14, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sleepTime', full_name='PBMsgHeroHouseList.PBMsgHero.sleepTime', index=14,
      number=15, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cityIndex', full_name='PBMsgHeroHouseList.PBMsgHero.cityIndex', index=15,
      number=16, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='slot', full_name='PBMsgHeroHouseList.PBMsgHero.slot', index=16,
      number=17, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=290,
  serialized_end=695,
)

_PBMSGHEROHOUSELIST = _descriptor.Descriptor(
  name='PBMsgHeroHouseList',
  full_name='PBMsgHeroHouseList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='heroHouseSlots', full_name='PBMsgHeroHouseList.heroHouseSlots', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='opennedSlot', full_name='PBMsgHeroHouseList.opennedSlot', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='unlockSlotDesc', full_name='PBMsgHeroHouseList.unlockSlotDesc', index=2,
      number=3, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hero', full_name='PBMsgHeroHouseList.hero', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_PBMSGHEROHOUSELIST_PBMSGSKILLACTIVED, _PBMSGHEROHOUSELIST_PBMSGHERO, ],
  enum_types=[
    _PBMSGHEROHOUSELIST_PBMSGHEROSTATUS,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=29,
  serialized_end=809,
)

_PBMSGHEROHOUSELIST_PBMSGSKILLACTIVED.containing_type = _PBMSGHEROHOUSELIST;
_PBMSGHEROHOUSELIST_PBMSGHERO.fields_by_name['status'].enum_type = _PBMSGHEROHOUSELIST_PBMSGHEROSTATUS
_PBMSGHEROHOUSELIST_PBMSGHERO.fields_by_name['skill'].message_type = _PBMSGHEROHOUSELIST_PBMSGSKILLACTIVED
_PBMSGHEROHOUSELIST_PBMSGHERO.fields_by_name['fate'].message_type = _PBMSGHEROHOUSELIST_PBMSGSKILLACTIVED
_PBMSGHEROHOUSELIST_PBMSGHERO.containing_type = _PBMSGHEROHOUSELIST;
_PBMSGHEROHOUSELIST.fields_by_name['hero'].message_type = _PBMSGHEROHOUSELIST_PBMSGHERO
_PBMSGHEROHOUSELIST_PBMSGHEROSTATUS.containing_type = _PBMSGHEROHOUSELIST;
DESCRIPTOR.message_types_by_name['PBMsgHeroHouseList'] = _PBMSGHEROHOUSELIST

class PBMsgHeroHouseList(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType

  class PBMsgSkillActived(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _PBMSGHEROHOUSELIST_PBMSGSKILLACTIVED

    # @@protoc_insertion_point(class_scope:PBMsgHeroHouseList.PBMsgSkillActived)

  class PBMsgHero(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _PBMSGHEROHOUSELIST_PBMSGHERO

    # @@protoc_insertion_point(class_scope:PBMsgHeroHouseList.PBMsgHero)
  DESCRIPTOR = _PBMSGHEROHOUSELIST

  # @@protoc_insertion_point(class_scope:PBMsgHeroHouseList)


# @@protoc_insertion_point(module_scope)
