# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PBMsgBoostHero.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='PBMsgBoostHero.proto',
  package='',
  serialized_pb='\n\x14PBMsgBoostHero.proto\"\xb8\x04\n\x0ePBMsgBoostHero\x12\x12\n\nuserHeroId\x18\x01 \x02(\x03\x12/\n\x06status\x18\x02 \x01(\x0e\x32\x1f.PBMsgBoostHero.PBMsgHeroStatus\x12\r\n\x05level\x18\x03 \x01(\x05\x12\n\n\x02hp\x18\x04 \x01(\x05\x12\x0e\n\x06\x61ttack\x18\x05 \x01(\x05\x12\x0c\n\x04load\x18\x06 \x01(\x05\x12\r\n\x05might\x18\x07 \x01(\x05\x12\x30\n\x05skill\x18\x08 \x03(\x0b\x32!.PBMsgBoostHero.PBMsgSkillActived\x12/\n\x04\x66\x61te\x18\t \x03(\x0b\x32!.PBMsgBoostHero.PBMsgSkillActived\x12\x0f\n\x07levelUp\x18\n \x02(\x08\x12\x0e\n\x06renown\x18\x0b \x02(\x05\x12\x17\n\x0fnextLevelRenown\x18\x0c \x01(\x05\x12\x0e\n\x06itemId\x18\r \x02(\x05\x1az\n\x11PBMsgSkillActived\x12\n\n\x02id\x18\x01 \x02(\x05\x12\x0f\n\x07\x61\x63tived\x18\x02 \x02(\x08\x12\n\n\x02lv\x18\x03 \x01(\x05\x12\x0c\n\x04hero\x18\x04 \x01(\x05\x12\x0c\n\x04gear\x18\x05 \x01(\x05\x12\x10\n\x08\x65\x66\x66\x65\x63tId\x18\x06 \x01(\x05\x12\x0e\n\x06\x65\x66\x66\x65\x63t\x18\x07 \x03(\t\"p\n\x0fPBMsgHeroStatus\x12\x0c\n\x08UNLOCKED\x10\x01\x12\x16\n\x12IN_CITY_DO_NOTHING\x10\x02\x12\x14\n\x10IN_CITY_IN_MARCH\x10\x03\x12\x11\n\rIN_CITY_SLEEP\x10\x04\x12\x0e\n\nIN_NO_CITY\x10\x05')



_PBMSGBOOSTHERO_PBMSGHEROSTATUS = _descriptor.EnumDescriptor(
  name='PBMsgHeroStatus',
  full_name='PBMsgBoostHero.PBMsgHeroStatus',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNLOCKED', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='IN_CITY_DO_NOTHING', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='IN_CITY_IN_MARCH', index=2, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='IN_CITY_SLEEP', index=3, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='IN_NO_CITY', index=4, number=5,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=481,
  serialized_end=593,
)


_PBMSGBOOSTHERO_PBMSGSKILLACTIVED = _descriptor.Descriptor(
  name='PBMsgSkillActived',
  full_name='PBMsgBoostHero.PBMsgSkillActived',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='PBMsgBoostHero.PBMsgSkillActived.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='actived', full_name='PBMsgBoostHero.PBMsgSkillActived.actived', index=1,
      number=2, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lv', full_name='PBMsgBoostHero.PBMsgSkillActived.lv', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hero', full_name='PBMsgBoostHero.PBMsgSkillActived.hero', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gear', full_name='PBMsgBoostHero.PBMsgSkillActived.gear', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='effectId', full_name='PBMsgBoostHero.PBMsgSkillActived.effectId', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='effect', full_name='PBMsgBoostHero.PBMsgSkillActived.effect', index=6,
      number=7, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=357,
  serialized_end=479,
)

_PBMSGBOOSTHERO = _descriptor.Descriptor(
  name='PBMsgBoostHero',
  full_name='PBMsgBoostHero',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='userHeroId', full_name='PBMsgBoostHero.userHeroId', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='status', full_name='PBMsgBoostHero.status', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='level', full_name='PBMsgBoostHero.level', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hp', full_name='PBMsgBoostHero.hp', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='attack', full_name='PBMsgBoostHero.attack', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='load', full_name='PBMsgBoostHero.load', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='might', full_name='PBMsgBoostHero.might', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='skill', full_name='PBMsgBoostHero.skill', index=7,
      number=8, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fate', full_name='PBMsgBoostHero.fate', index=8,
      number=9, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='levelUp', full_name='PBMsgBoostHero.levelUp', index=9,
      number=10, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='renown', full_name='PBMsgBoostHero.renown', index=10,
      number=11, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nextLevelRenown', full_name='PBMsgBoostHero.nextLevelRenown', index=11,
      number=12, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='itemId', full_name='PBMsgBoostHero.itemId', index=12,
      number=13, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_PBMSGBOOSTHERO_PBMSGSKILLACTIVED, ],
  enum_types=[
    _PBMSGBOOSTHERO_PBMSGHEROSTATUS,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=25,
  serialized_end=593,
)

_PBMSGBOOSTHERO_PBMSGSKILLACTIVED.containing_type = _PBMSGBOOSTHERO;
_PBMSGBOOSTHERO.fields_by_name['status'].enum_type = _PBMSGBOOSTHERO_PBMSGHEROSTATUS
_PBMSGBOOSTHERO.fields_by_name['skill'].message_type = _PBMSGBOOSTHERO_PBMSGSKILLACTIVED
_PBMSGBOOSTHERO.fields_by_name['fate'].message_type = _PBMSGBOOSTHERO_PBMSGSKILLACTIVED
_PBMSGBOOSTHERO_PBMSGHEROSTATUS.containing_type = _PBMSGBOOSTHERO;
DESCRIPTOR.message_types_by_name['PBMsgBoostHero'] = _PBMSGBOOSTHERO

class PBMsgBoostHero(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType

  class PBMsgSkillActived(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _PBMSGBOOSTHERO_PBMSGSKILLACTIVED

    # @@protoc_insertion_point(class_scope:PBMsgBoostHero.PBMsgSkillActived)
  DESCRIPTOR = _PBMSGBOOSTHERO

  # @@protoc_insertion_point(class_scope:PBMsgBoostHero)


# @@protoc_insertion_point(module_scope)
