# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PBMsgReqProcessHeroExplore.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='PBMsgReqProcessHeroExplore.proto',
  package='',
  serialized_pb='\n PBMsgReqProcessHeroExplore.proto\"U\n\x1aPBMsgReqProcessHeroExplore\x12\x0b\n\x03hid\x18\x01 \x02(\x03\x12\x0b\n\x03\x65id\x18\x02 \x02(\x03\x12\x0f\n\x07useGems\x18\x03 \x02(\x08\x12\x0c\n\x04gems\x18\x04 \x02(\x05')




_PBMSGREQPROCESSHEROEXPLORE = _descriptor.Descriptor(
  name='PBMsgReqProcessHeroExplore',
  full_name='PBMsgReqProcessHeroExplore',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='hid', full_name='PBMsgReqProcessHeroExplore.hid', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='eid', full_name='PBMsgReqProcessHeroExplore.eid', index=1,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='useGems', full_name='PBMsgReqProcessHeroExplore.useGems', index=2,
      number=3, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gems', full_name='PBMsgReqProcessHeroExplore.gems', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=36,
  serialized_end=121,
)

DESCRIPTOR.message_types_by_name['PBMsgReqProcessHeroExplore'] = _PBMSGREQPROCESSHEROEXPLORE

class PBMsgReqProcessHeroExplore(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PBMSGREQPROCESSHEROEXPLORE

  # @@protoc_insertion_point(class_scope:PBMsgReqProcessHeroExplore)


# @@protoc_insertion_point(module_scope)
