# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PBMsgProcessHeroExplore.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='PBMsgProcessHeroExplore.proto',
  package='',
  serialized_pb='\n\x1dPBMsgProcessHeroExplore.proto\"~\n\x17PBMsgProcessHeroExplore\x12\x11\n\texploreId\x18\x01 \x02(\x03\x12\x10\n\x08strength\x18\x02 \x02(\x05\x12\x0e\n\x06itemId\x18\x03 \x01(\x05\x12\x11\n\titemCount\x18\x04 \x01(\x05\x12\x0c\n\x04gems\x18\x05 \x01(\x05\x12\r\n\x05gemsN\x18\x06 \x02(\x05')




_PBMSGPROCESSHEROEXPLORE = _descriptor.Descriptor(
  name='PBMsgProcessHeroExplore',
  full_name='PBMsgProcessHeroExplore',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='exploreId', full_name='PBMsgProcessHeroExplore.exploreId', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='strength', full_name='PBMsgProcessHeroExplore.strength', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='itemId', full_name='PBMsgProcessHeroExplore.itemId', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='itemCount', full_name='PBMsgProcessHeroExplore.itemCount', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gems', full_name='PBMsgProcessHeroExplore.gems', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gemsN', full_name='PBMsgProcessHeroExplore.gemsN', index=5,
      number=6, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=33,
  serialized_end=159,
)

DESCRIPTOR.message_types_by_name['PBMsgProcessHeroExplore'] = _PBMSGPROCESSHEROEXPLORE

class PBMsgProcessHeroExplore(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PBMSGPROCESSHEROEXPLORE

  # @@protoc_insertion_point(class_scope:PBMsgProcessHeroExplore)


# @@protoc_insertion_point(module_scope)
