# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PBMsgMystryChest.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='PBMsgMystryChest.proto',
  package='',
  serialized_pb='\n\x16PBMsgMystryChest.proto\"?\n\x14MystryChestLevelData\x12\n\n\x02id\x18\x01 \x02(\x05\x12\x0c\n\x04icon\x18\x02 \x02(\t\x12\r\n\x05level\x18\x03 \x02(\x05\"3\n\x0fMysteryDropGear\x12\x10\n\x08geartype\x18\x01 \x02(\x05\x12\x0e\n\x06weight\x18\x02 \x02(\x05\"\xfa\x01\n\x0fMystryChestData\x12\n\n\x02id\x18\x01 \x02(\x05\x12\x0c\n\x04icon\x18\x02 \x02(\t\x12\x11\n\tstarttime\x18\x03 \x02(\x03\x12\x12\n\nfinishtime\x18\x04 \x02(\x03\x12\r\n\x05price\x18\x05 \x02(\x05\x12\x0f\n\x07\x66orSale\x18\x06 \x02(\x08\x12\x19\n\x11\x64iscountStarttime\x18\x07 \x02(\x03\x12\x1a\n\x12\x64iscountFinishtime\x18\x08 \x02(\x03\x12\x15\n\rdiscountPrice\x18\t \x02(\x05\x12\"\n\x08\x64ropGear\x18\n \x03(\x0b\x32\x10.MysteryDropGear\x12\x14\n\x08serverId\x18\x0b \x03(\x05\x42\x02\x10\x01\"\x7f\n\x13MystryChestResponse\x12\x0f\n\x07version\x18\x01 \x02(\x03\x12\x1e\n\x04\x64\x61ta\x18\x02 \x03(\x0b\x32\x10.MystryChestData\x12$\n\x05ldata\x18\x03 \x03(\x0b\x32\x15.MystryChestLevelData\x12\x11\n\x05order\x18\x04 \x03(\x05\x42\x02\x10\x01\"%\n\x12MystryChestRequest\x12\x0f\n\x07version\x18\x01 \x02(\x03')




_MYSTRYCHESTLEVELDATA = _descriptor.Descriptor(
  name='MystryChestLevelData',
  full_name='MystryChestLevelData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='MystryChestLevelData.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='icon', full_name='MystryChestLevelData.icon', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='level', full_name='MystryChestLevelData.level', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=26,
  serialized_end=89,
)


_MYSTERYDROPGEAR = _descriptor.Descriptor(
  name='MysteryDropGear',
  full_name='MysteryDropGear',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='geartype', full_name='MysteryDropGear.geartype', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='weight', full_name='MysteryDropGear.weight', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=91,
  serialized_end=142,
)


_MYSTRYCHESTDATA = _descriptor.Descriptor(
  name='MystryChestData',
  full_name='MystryChestData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='MystryChestData.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='icon', full_name='MystryChestData.icon', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='starttime', full_name='MystryChestData.starttime', index=2,
      number=3, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='finishtime', full_name='MystryChestData.finishtime', index=3,
      number=4, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='price', full_name='MystryChestData.price', index=4,
      number=5, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='forSale', full_name='MystryChestData.forSale', index=5,
      number=6, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='discountStarttime', full_name='MystryChestData.discountStarttime', index=6,
      number=7, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='discountFinishtime', full_name='MystryChestData.discountFinishtime', index=7,
      number=8, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='discountPrice', full_name='MystryChestData.discountPrice', index=8,
      number=9, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dropGear', full_name='MystryChestData.dropGear', index=9,
      number=10, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='serverId', full_name='MystryChestData.serverId', index=10,
      number=11, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\020\001')),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=145,
  serialized_end=395,
)


_MYSTRYCHESTRESPONSE = _descriptor.Descriptor(
  name='MystryChestResponse',
  full_name='MystryChestResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='MystryChestResponse.version', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data', full_name='MystryChestResponse.data', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ldata', full_name='MystryChestResponse.ldata', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='order', full_name='MystryChestResponse.order', index=3,
      number=4, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\020\001')),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=397,
  serialized_end=524,
)


_MYSTRYCHESTREQUEST = _descriptor.Descriptor(
  name='MystryChestRequest',
  full_name='MystryChestRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='MystryChestRequest.version', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=526,
  serialized_end=563,
)

_MYSTRYCHESTDATA.fields_by_name['dropGear'].message_type = _MYSTERYDROPGEAR
_MYSTRYCHESTRESPONSE.fields_by_name['data'].message_type = _MYSTRYCHESTDATA
_MYSTRYCHESTRESPONSE.fields_by_name['ldata'].message_type = _MYSTRYCHESTLEVELDATA
DESCRIPTOR.message_types_by_name['MystryChestLevelData'] = _MYSTRYCHESTLEVELDATA
DESCRIPTOR.message_types_by_name['MysteryDropGear'] = _MYSTERYDROPGEAR
DESCRIPTOR.message_types_by_name['MystryChestData'] = _MYSTRYCHESTDATA
DESCRIPTOR.message_types_by_name['MystryChestResponse'] = _MYSTRYCHESTRESPONSE
DESCRIPTOR.message_types_by_name['MystryChestRequest'] = _MYSTRYCHESTREQUEST

class MystryChestLevelData(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MYSTRYCHESTLEVELDATA

  # @@protoc_insertion_point(class_scope:MystryChestLevelData)

class MysteryDropGear(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MYSTERYDROPGEAR

  # @@protoc_insertion_point(class_scope:MysteryDropGear)

class MystryChestData(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MYSTRYCHESTDATA

  # @@protoc_insertion_point(class_scope:MystryChestData)

class MystryChestResponse(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MYSTRYCHESTRESPONSE

  # @@protoc_insertion_point(class_scope:MystryChestResponse)

class MystryChestRequest(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MYSTRYCHESTREQUEST

  # @@protoc_insertion_point(class_scope:MystryChestRequest)


_MYSTRYCHESTDATA.fields_by_name['serverId'].has_options = True
_MYSTRYCHESTDATA.fields_by_name['serverId']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\020\001')
_MYSTRYCHESTRESPONSE.fields_by_name['order'].has_options = True
_MYSTRYCHESTRESPONSE.fields_by_name['order']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\020\001')
# @@protoc_insertion_point(module_scope)
