# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PBMsgReqUnassignHero.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='PBMsgReqUnassignHero.proto',
  package='',
  serialized_pb='\n\x1aPBMsgReqUnassignHero.proto\"0\n\x14PBMsgReqUnassignHero\x12\x0b\n\x03\x63id\x18\x01 \x02(\x03\x12\x0b\n\x03hid\x18\x02 \x02(\x03')




_PBMSGREQUNASSIGNHERO = _descriptor.Descriptor(
  name='PBMsgReqUnassignHero',
  full_name='PBMsgReqUnassignHero',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cid', full_name='PBMsgReqUnassignHero.cid', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hid', full_name='PBMsgReqUnassignHero.hid', index=1,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=30,
  serialized_end=78,
)

DESCRIPTOR.message_types_by_name['PBMsgReqUnassignHero'] = _PBMSGREQUNASSIGNHERO

class PBMsgReqUnassignHero(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PBMSGREQUNASSIGNHERO

  # @@protoc_insertion_point(class_scope:PBMsgReqUnassignHero)


# @@protoc_insertion_point(module_scope)
