# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PBMsgReqPveInfo.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='PBMsgReqPveInfo.proto',
  package='',
  serialized_pb='\n\x15PBMsgReqPveInfo.proto\"\"\n\x0fPBMsgReqPveInfo\x12\x0f\n\x07infoVer\x18\x01 \x01(\t')




_PBMSGREQPVEINFO = _descriptor.Descriptor(
  name='PBMsgReqPveInfo',
  full_name='PBMsgReqPveInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='infoVer', full_name='PBMsgReqPveInfo.infoVer', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=25,
  serialized_end=59,
)

DESCRIPTOR.message_types_by_name['PBMsgReqPveInfo'] = _PBMSGREQPVEINFO

class PBMsgReqPveInfo(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PBMSGREQPVEINFO

  # @@protoc_insertion_point(class_scope:PBMsgReqPveInfo)


# @@protoc_insertion_point(module_scope)
