# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PBMsgReqInitHeroExplore.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='PBMsgReqInitHeroExplore.proto',
  package='',
  serialized_pb='\n\x1dPBMsgReqInitHeroExplore.proto\"3\n\x17PBMsgReqInitHeroExplore\x12\x0b\n\x03\x63id\x18\x01 \x02(\x03\x12\x0b\n\x03hid\x18\x02 \x02(\x03')




_PBMSGREQINITHEROEXPLORE = _descriptor.Descriptor(
  name='PBMsgReqInitHeroExplore',
  full_name='PBMsgReqInitHeroExplore',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cid', full_name='PBMsgReqInitHeroExplore.cid', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hid', full_name='PBMsgReqInitHeroExplore.hid', index=1,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=33,
  serialized_end=84,
)

DESCRIPTOR.message_types_by_name['PBMsgReqInitHeroExplore'] = _PBMSGREQINITHEROEXPLORE

class PBMsgReqInitHeroExplore(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PBMSGREQINITHEROEXPLORE

  # @@protoc_insertion_point(class_scope:PBMsgReqInitHeroExplore)


# @@protoc_insertion_point(module_scope)
