"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['phpTest.py']
DATA_FILES = ['tools.ui','update.ui','couput.ui','addProto.ui','Ui_update.py']
OPTIONS = {
    'argv_emulation': False,
    'optimize': 2,
    'includes':['sip','unzip','readconfig','addProto','protocol','update', 'PyQt4', 'PyQt4.QtGui', 'PyQt4.QtCore','httplib','hashlib','sys','base64','os','ConfigParser','command']
    }
#ICON={'Mac':'./PythonApplet.icns'}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
    #console=[{"icon_resource":[(1,"PythonApplet.icns")]}]
)
