# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/chenbiao/Documents/workspaces/tools/tools.ui'
#
# Created: Mon Mar 31 14:51:46 2014
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(800, 600)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 801, 581))
        self.tabWidget.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.testPlanEdit = QtGui.QTextEdit(self.tab)
        self.testPlanEdit.setGeometry(QtCore.QRect(0, 80, 791, 381))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.testPlanEdit.setFont(font)
        self.testPlanEdit.setFrameShape(QtGui.QFrame.Box)
        self.testPlanEdit.setFrameShadow(QtGui.QFrame.Raised)
        self.testPlanEdit.setObjectName(_fromUtf8("testPlanEdit"))
        self.label_8 = QtGui.QLabel(self.tab)
        self.label_8.setGeometry(QtCore.QRect(0, 50, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.runButton = QtGui.QPushButton(self.tab)
        self.runButton.setGeometry(QtCore.QRect(660, 480, 114, 51))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Lucida Grande"))
        font.setPointSize(19)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setKerning(True)
        self.runButton.setFont(font)
        self.runButton.setObjectName(_fromUtf8("runButton"))
        self.saveButton = QtGui.QPushButton(self.tab)
        self.saveButton.setGeometry(QtCore.QRect(520, 480, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.saveButton.setFont(font)
        self.saveButton.setObjectName(_fromUtf8("saveButton"))
        self.generateScriptButton = QtGui.QPushButton(self.tab)
        self.generateScriptButton.setGeometry(QtCore.QRect(10, 490, 161, 32))
        self.generateScriptButton.setObjectName(_fromUtf8("generateScriptButton"))
        self.checkBox = QtGui.QCheckBox(self.tab)
        self.checkBox.setGeometry(QtCore.QRect(210, 489, 87, 31))
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.label_9 = QtGui.QLabel(self.tab)
        self.label_9.setGeometry(QtCore.QRect(1, 9, 81, 31))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.autoUrlEdit = QtGui.QTextEdit(self.tab)
        self.autoUrlEdit.setGeometry(QtCore.QRect(90, 10, 601, 31))
        self.autoUrlEdit.setObjectName(_fromUtf8("autoUrlEdit"))
        self.openButton = QtGui.QPushButton(self.tab)
        self.openButton.setGeometry(QtCore.QRect(693, 10, 91, 32))
        self.openButton.setObjectName(_fromUtf8("openButton"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.listView = QtGui.QListView(self.tab_2)
        self.listView.setGeometry(QtCore.QRect(0, 0, 261, 511))
        self.listView.setObjectName(_fromUtf8("listView"))
        self.label = QtGui.QLabel(self.tab_2)
        self.label.setGeometry(QtCore.QRect(260, 200, 71, 31))
        self.label.setMargin(0)
        self.label.setIndent(16)
        self.label.setObjectName(_fromUtf8("label"))
        self.textEdit = QtGui.QTextEdit(self.tab_2)
        self.textEdit.setGeometry(QtCore.QRect(270, 70, 521, 121))
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.textEdit_2 = QtGui.QTextEdit(self.tab_2)
        self.textEdit_2.setGeometry(QtCore.QRect(320, 200, 81, 31))
        self.textEdit_2.setObjectName(_fromUtf8("textEdit_2"))
        self.label_2 = QtGui.QLabel(self.tab_2)
        self.label_2.setGeometry(QtCore.QRect(270, 0, 71, 21))
        self.label_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.label_2.setTextFormat(QtCore.Qt.PlainText)
        self.label_2.setScaledContents(False)
        self.label_2.setWordWrap(False)
        self.label_2.setMargin(2)
        self.label_2.setIndent(9)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.tab_2)
        self.label_3.setGeometry(QtCore.QRect(270, 240, 81, 21))
        self.label_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.label_3.setTextFormat(QtCore.Qt.PlainText)
        self.label_3.setMargin(0)
        self.label_3.setIndent(10)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.pushButton = QtGui.QPushButton(self.tab_2)
        self.pushButton.setGeometry(QtCore.QRect(680, 200, 101, 31))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.label_4 = QtGui.QLabel(self.tab_2)
        self.label_4.setGeometry(QtCore.QRect(270, 30, 71, 21))
        self.label_4.setFrameShadow(QtGui.QFrame.Plain)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.textEdit_3 = QtGui.QTextEdit(self.tab_2)
        self.textEdit_3.setGeometry(QtCore.QRect(350, 30, 441, 31))
        self.textEdit_3.setObjectName(_fromUtf8("textEdit_3"))
        self.label_5 = QtGui.QLabel(self.tab_2)
        self.label_5.setGeometry(QtCore.QRect(430, 205, 101, 21))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.textEdit_4 = QtGui.QTextEdit(self.tab_2)
        self.textEdit_4.setGeometry(QtCore.QRect(530, 200, 131, 31))
        self.textEdit_4.setObjectName(_fromUtf8("textEdit_4"))
        self.pushButton_2 = QtGui.QPushButton(self.tab_2)
        self.pushButton_2.setGeometry(QtCore.QRect(710, 240, 71, 23))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.textBrowser = QtGui.QTextBrowser(self.tab_2)
        self.textBrowser.setGeometry(QtCore.QRect(270, 270, 521, 261))
        self.textBrowser.setObjectName(_fromUtf8("textBrowser"))
        self.addProtoBuf = QtGui.QPushButton(self.tab_2)
        self.addProtoBuf.setGeometry(QtCore.QRect(0, 510, 81, 21))
        self.addProtoBuf.setObjectName(_fromUtf8("addProtoBuf"))
        self.deleteProtoBuf = QtGui.QPushButton(self.tab_2)
        self.deleteProtoBuf.setGeometry(QtCore.QRect(80, 510, 81, 21))
        self.deleteProtoBuf.setObjectName(_fromUtf8("deleteProtoBuf"))
        self.refreshList = QtGui.QPushButton(self.tab_2)
        self.refreshList.setGeometry(QtCore.QRect(160, 510, 101, 21))
        self.refreshList.setObjectName(_fromUtf8("refreshList"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.textEdit_5 = QtGui.QTextEdit(self.tab_3)
        self.textEdit_5.setGeometry(QtCore.QRect(20, 40, 761, 181))
        self.textEdit_5.setObjectName(_fromUtf8("textEdit_5"))
        self.label_6 = QtGui.QLabel(self.tab_3)
        self.label_6.setGeometry(QtCore.QRect(20, 10, 91, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.pushButton_3 = QtGui.QPushButton(self.tab_3)
        self.pushButton_3.setGeometry(QtCore.QRect(170, 240, 451, 41))
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.textBrowser_2 = QtGui.QTextBrowser(self.tab_3)
        self.textBrowser_2.setGeometry(QtCore.QRect(20, 320, 761, 181))
        self.textBrowser_2.setObjectName(_fromUtf8("textBrowser_2"))
        self.label_7 = QtGui.QLabel(self.tab_3)
        self.label_7.setGeometry(QtCore.QRect(20, 286, 71, 20))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.listView_2 = QtGui.QListView(self.tab_4)
        self.listView_2.setGeometry(QtCore.QRect(0, 0, 256, 531))
        self.listView_2.setObjectName(_fromUtf8("listView_2"))
        self.descriptionText = QtGui.QTextBrowser(self.tab_4)
        self.descriptionText.setGeometry(QtCore.QRect(270, 141, 511, 61))
        self.descriptionText.setObjectName(_fromUtf8("descriptionText"))
        self.argumentText = QtGui.QTextEdit(self.tab_4)
        self.argumentText.setGeometry(QtCore.QRect(270, 30, 511, 31))
        self.argumentText.setObjectName(_fromUtf8("argumentText"))
        self.label_10 = QtGui.QLabel(self.tab_4)
        self.label_10.setGeometry(QtCore.QRect(270, 110, 91, 21))
        self.label_10.setFrameShape(QtGui.QFrame.WinPanel)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_11 = QtGui.QLabel(self.tab_4)
        self.label_11.setGeometry(QtCore.QRect(270, 6, 81, 20))
        self.label_11.setFrameShape(QtGui.QFrame.WinPanel)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_12 = QtGui.QLabel(self.tab_4)
        self.label_12.setGeometry(QtCore.QRect(270, 250, 71, 21))
        self.label_12.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_12.setFrameShape(QtGui.QFrame.WinPanel)
        self.label_12.setTextFormat(QtCore.Qt.PlainText)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.scriptResponse = QtGui.QTextBrowser(self.tab_4)
        self.scriptResponse.setGeometry(QtCore.QRect(270, 280, 511, 251))
        self.scriptResponse.setObjectName(_fromUtf8("scriptResponse"))
        self.runScriptBtn = QtGui.QPushButton(self.tab_4)
        self.runScriptBtn.setGeometry(QtCore.QRect(270, 210, 511, 41))
        self.runScriptBtn.setObjectName(_fromUtf8("runScriptBtn"))
        self.clearScriptResponse = QtGui.QPushButton(self.tab_4)
        self.clearScriptResponse.setGeometry(QtCore.QRect(660, 250, 114, 32))
        self.clearScriptResponse.setObjectName(_fromUtf8("clearScriptResponse"))
        self.label_13 = QtGui.QLabel(self.tab_4)
        self.label_13.setGeometry(QtCore.QRect(270, 80, 31, 16))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.URLText = QtGui.QTextEdit(self.tab_4)
        self.URLText.setGeometry(QtCore.QRect(310, 70, 471, 31))
        self.URLText.setObjectName(_fromUtf8("URLText"))
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuSetting = QtGui.QMenu(self.menubar)
        self.menuSetting.setObjectName(_fromUtf8("menuSetting"))
        self.menuProtocol_config_file = QtGui.QMenu(self.menuSetting)
        self.menuProtocol_config_file.setObjectName(_fromUtf8("menuProtocol_config_file"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionUpdate = QtGui.QAction(MainWindow)
        self.actionUpdate.setObjectName(_fromUtf8("actionUpdate"))
        self.actionChoose_config = QtGui.QAction(MainWindow)
        self.actionChoose_config.setObjectName(_fromUtf8("actionChoose_config"))
        self.actionImport = QtGui.QAction(MainWindow)
        self.actionImport.setObjectName(_fromUtf8("actionImport"))
        self.actionExport = QtGui.QAction(MainWindow)
        self.actionExport.setObjectName(_fromUtf8("actionExport"))
        self.actionImport_2 = QtGui.QAction(MainWindow)
        self.actionImport_2.setObjectName(_fromUtf8("actionImport_2"))
        self.menuProtocol_config_file.addAction(self.actionImport)
        self.menuProtocol_config_file.addAction(self.actionExport)
        self.menuSetting.addAction(self.actionUpdate)
        self.menuSetting.addSeparator()
        self.menuSetting.addAction(self.menuProtocol_config_file.menuAction())
        self.menubar.addAction(self.menuSetting.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "QATools", None))
        self.label_8.setText(_translate("MainWindow", "Test Plan:", None))
        self.runButton.setText(_translate("MainWindow", "run", None))
        self.saveButton.setText(_translate("MainWindow", "save", None))
        self.generateScriptButton.setText(_translate("MainWindow", "generate script", None))
        self.checkBox.setText(_translate("MainWindow", "record", None))
        self.label_9.setText(_translate("MainWindow", "auto file url:", None))
        self.openButton.setText(_translate("MainWindow", "open", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "UIauto", None))
        self.label.setText(_translate("MainWindow", "loops:", None))
        self.label_2.setText(_translate("MainWindow", "request", None))
        self.label_3.setText(_translate("MainWindow", "response", None))
        self.pushButton.setText(_translate("MainWindow", "send", None))
        self.label_4.setText(_translate("MainWindow", "server url", None))
        self.label_5.setText(_translate("MainWindow", "protocol name:", None))
        self.pushButton_2.setText(_translate("MainWindow", "clear", None))
        self.addProtoBuf.setText(_translate("MainWindow", "+", None))
        self.deleteProtoBuf.setText(_translate("MainWindow", "-", None))
        self.refreshList.setText(_translate("MainWindow", "refresh", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "protocol", None))
        self.label_6.setText(_translate("MainWindow", "base64 data:", None))
        self.pushButton_3.setText(_translate("MainWindow", "decode", None))
        self.label_7.setText(_translate("MainWindow", "URL data:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "b64decode", None))
        self.label_10.setText(_translate("MainWindow", "description：", None))
        self.label_11.setText(_translate("MainWindow", "argument：", None))
        self.label_12.setText(_translate("MainWindow", "response：", None))
        self.runScriptBtn.setText(_translate("MainWindow", "run script", None))
        self.clearScriptResponse.setText(_translate("MainWindow", "clear", None))
        self.label_13.setText(_translate("MainWindow", "URL:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "script", None))
        self.menuSetting.setTitle(_translate("MainWindow", "settings", None))
        self.menuProtocol_config_file.setTitle(_translate("MainWindow", "protocol config file", None))
        self.actionUpdate.setText(_translate("MainWindow", "update", None))
        self.actionChoose_config.setText(_translate("MainWindow", "choose configurations", None))
        self.actionImport.setText(_translate("MainWindow", "import", None))
        self.actionExport.setText(_translate("MainWindow", "export", None))
        self.actionImport_2.setText(_translate("MainWindow", "import", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

